class LanguagePackage {
  Map id = new Map();
  LanguagePackage(this.id);
}

// ignore: non_constant_identifier_names
LanguagePackage English = LanguagePackage({
  "app_title": "Canokey Client",
  "home_page": "Home",
  "NFC_availability": "Equipment NFC Availability",
  "credentials_page": "Credientials",
  "setting_page": "Settings",
  "about_page": "About",
  "help_page": "Help",
  "dialog_attention": "Attention!",
  "dialog_removeConfirm": "Are you sure to remove this record?",
  "dialog_yes": "Yes",
  "dialog_no": "No",
  "canokey_name": "Canokey Name",
  "canokey_id": "Canokey ID",
  "canokey_standard": "Standard",
  "canokey_OATH": "OATH Application",
  "language": "Language Switch",
  "powered": "Powered By Canokeys Develop Group",
  "warning": "Warning!",
  "success": "Success!",
  "failed":"Failed!",
  "result_Addfailed":"Something Went Wrong!Please Try Again.Maybe This Account Has Been Added Before?",
  "result_success":"Add Account Successfully.",
  "result_Confailed":"Something Went Wrong!Please Try Again.The Connection Went Wrong.",
  "connect":"Please use NFC to connect Canokey.We are adding new account now.",
  "credential_null":"Credentials in Canokey are null!",
  "account_name":"Account Name",
  "account_key":"Key(In Base32)",
  "refresh":"Refreshing Credentials Now.Please Connecting To Canokey.",
  "namedCanokey":"Named your Canokey",
  "input":"Input...",
  "detectBefore":"This Canokey has been written before!",
  "email":"Email",
  "github":"Visit Github",
  "finished":"Finished",
  "intruction":"App Instruction",
  "confirm":"Confirm",
  "connecting":"Keep your Canokey close to your device.Usually,at the back of device.",
  "poll_timeout":"Connecting failed or time our.Please retry connection.",
  "refresh_success":"Refreshing succeed!"
});

// ignore: non_constant_identifier_names
LanguagePackage Chinese = LanguagePackage({
  "app_title": "Canokey 客户端",
  "home_page": "主页",
  "NFC_availability": "设备NFC启用情况",
  "credentials_page": "证书",
  "setting_page": "设定",
  "about_page": "关于",
  "help_page": "帮助",
  "dialog_attention": "注意！",
  "dialog_removeConfirm": "你确定要移除该记录吗？",
  "dialog_yes": "是",
  "dialog_no": "否",
  "canokey_name": "Canokey 名称",
  "canokey_id": "Canokey ID",
  "canokey_standard": "标准",
  "canokey_OATH": "OATH应用",
  "language": "语言切换",
  "powered": "由Canokey团队提供技术支持",
  "warning": "警告!",
  "success": "成功!",
  "result_success":"账户添加成功！",
  "failed":"失败！",
  "result_Addfailed":"出错了！请重试。或许这个账户已经被添加过？",
  "result_Confailed":"出错了！请重试。与Canokey连接失败",
  "connect":"请通过NFC连接Canokey，我们正在尝试创建新账户",
  "credential_null":"Canokey中没有证书!",
  "account_name":"账户名称",
  "account_key":"密钥(Base 32格式）",
  "refresh":"正在刷新证书。请将Canokey连接至设备。",
  "namedCanokey":"为您的Canokey命名",
  "input":"输入...",
  "detectBefore":"此Canokey已经被录入过！",
  "email":"电子邮箱",
  "github":"访问Github仓库",
  "finished":"完成",
  "instruction":"应用教程",
  "confirm":"确定",
  "connecting":"连接您的Canokey。通常情况下，将Canokey靠近设备后侧。",
  "poll_timeout":"连接失败或超时，请重新尝试连接。",
  "refresh_success":"成功刷新!"
});

// ignore: non_constant_identifier_names
LanguagePackage Japanese = LanguagePackage({
  "app_title": "Canokey クライアント ",
  "home_page": "ホームページ",
  "NFC_availability": "デバイスのNFC始動状況",
  "credentials_page": "証明書",
  "setting_page": "設定",
  "about_page": "アバウト",
  "help_page": "ヘルプ",
  "dialog_attention": "注意！",
  "dialog_removeConfirm": "記録を除去することを確認しますか？",
  "dialog_yes": "はい",
  "dialog_no": "いいえ",
  "canokey_name": "Canokey 名前",
  "canokey_id": "Canokey ID",
  "canokey_standard": "スタンダード",
  "canokey_OATH": "OATHアプリケーション",
  "language": "言語を切り替える",
  "powered": "技術サポートはCanokeyチームが行っている",
  "warning": "警告!",
  "success": "成功!",
  "result_success":"アカウント追加に成功！",
  "failed":"失敗！",
  "result_Addfailed":"ミス!再試行してください。このアカウントはすでに添付されているかもしれません。",
  "result_Confailed":"ミス!再試行してください。Canokeyとの接続に失敗する。",
  "connect":"请NFCを介してCanokeyに接続してください。新しいアカウントの作成を試みています",
  "credential_null":"Canokeyには証明書がない!",
  "account_name":"アカウント名",
  "account_key":"鍵(Base 32フォーマット)",
  "refresh":"正証明書を更新しています。デバイスにCanokeyを接続してください。",
  "namedCanokey":"貴方のCanokeyにちなんで名づけました",
  "input":"入力...",
  "detectBefore":"このCanokeyは既に収録されています!",
  "email":"電子メール",
  "github":"Github倉庫にアクセスする",
  "finished":"完成",
  "instruction":"応用教程",
  "confirm":"オッケー",
  "connecting":"Canokeyを接続します。通常、Canokeyをデバイスの背面に近づけます。",
  "poll_timeout":"接続に失敗したか、タイムアウトしました。もう一度接続してみてください。",
  "refresh_success":"正常に更新されました!"
});


